# Generated by Django 4.2 on 2023-04-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigIntegerField(primary_key='id', serialize=False)),
                ('title', models.TextField(max_length=250)),
                ('description', models.TextField(max_length=250)),
                ('originality_check', models.TextField(max_length=2500)),
                ('due_date', models.DateTimeField()),
                ('owner_id', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentMaterial',
            fields=[
                ('id', models.BigIntegerField(primary_key='id', serialize=False)),
                ('assignment_id', models.TextField(max_length=250)),
                ('link', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentStudent',
            fields=[
                ('id', models.BigIntegerField(primary_key='id', serialize=False)),
                ('assignment_id', models.TextField(max_length=250)),
                ('student_id', models.BigIntegerField()),
            ],
        ),
    ]
