# Generated by Django 4.2 on 2023-04-25 12:05

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='processed',
            field=models.TextField(default='YES', max_length=20),
        ),
    ]
