# Generated by Django 4.2 on 2023-04-25 12:07

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('teacher', '0002_assignment_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='processed',
            field=models.BooleanField(default=False, max_length=20),
        ),
    ]
