# Generated by Django 4.2 on 2023-04-25 12:17

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('teacher', '0004_assignment_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
