# Generated by Django 4.2 on 2023-04-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_alter_assignment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='id',
            field=models.BigIntegerField(auto_created=True, primary_key='id', serialize=False),
        ),
    ]
