# Generated by Django 4.2 on 2023-04-25 12:24

from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ('teacher', '0009_alter_assignment_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='due_date',
        ),
    ]
