# Generated by Django 4.2 on 2023-04-25 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0015_alter_assignments_created_at_alter_courses_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 25, 12, 51, 40, 813607, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='courses',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
