# Generated by Django 4.2 on 2023-04-25 20:38

import datetime

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('teacher', '0016_alter_assignments_created_at_alter_courses_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='created_at',
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 25, 20, 38, 14, 781570, tzinfo=datetime.timezone.utc)),
        ),
    ]
