# Generated by Django 4.2 on 2023-04-30 04:01

import datetime

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('teacher', '0017_alter_assignments_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='created_at',
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 30, 4, 1, 44, 951691, tzinfo=datetime.timezone.utc)),
        ),
    ]
