# Generated by Django 4.2 on 2023-05-02 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0021_alter_assignments_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 2, 13, 51, 29, 214249, tzinfo=datetime.timezone.utc)),
        ),
    ]
