# Generated by Django 4.2 on 2023-05-03 07:47

import datetime

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('teacher', '0023_alter_assignments_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='created_at',
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 3, 7, 47, 39, 613768, tzinfo=datetime.timezone.utc)),
        ),
    ]
