# Generated by Django 4.2 on 2023-05-03 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0026_alter_assignments_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 3, 8, 9, 22, 761177, tzinfo=datetime.timezone.utc)),
        ),
    ]
