# Generated by Django 4.2 on 2023-05-03 09:21

import datetime

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('teacher', '0028_alter_assignments_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='created_at',
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 3, 9, 21, 33, 388830, tzinfo=datetime.timezone.utc)),
        ),
    ]
