# Generated by Django 4.2 on 2023-05-03 10:25

import datetime

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('teacher', '0029_alter_assignments_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='created_at',
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 3, 10, 25, 39, 892165, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_id',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='courses',
            name='owner_id',
            field=models.TextField(max_length=50),
        ),
    ]
