# Generated by Django 4.2 on 2023-05-08 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0034_alter_assignments_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 8, 11, 0, 37, 870808, tzinfo=datetime.timezone.utc)),
        ),
    ]
