# Generated by Django 4.2 on 2023-05-08 20:44

import datetime

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('teacher', '0035_alter_assignments_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='due_date',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='assignments',
            name='due_time',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='created_at',
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 8, 20, 44, 50, 979390, tzinfo=datetime.timezone.utc)),
        ),
    ]
