# Generated by Django 4.2 on 2023-05-08 21:36

import datetime

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('teacher', '0037_alter_assignments_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentmaterials',
            old_name='link',
            new_name='google_drive_id',
        ),
        migrations.AlterField(
            model_name='assignmentmaterials',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='created_at',
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 8, 21, 36, 20, 402906, tzinfo=datetime.timezone.utc)),
        ),
    ]
