# Generated by Django 4.2 on 2023-05-09 10:19

import datetime

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0038_rename_link_assignmentmaterials_google_drive_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 9, 10, 18, 45, 632053, tzinfo=datetime.timezone.utc)),
        ),
    ]
