# Generated by Django 4.2 on 2023-05-11 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0041_alter_assignments_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 11, 9, 9, 41, 341070, tzinfo=datetime.timezone.utc)),
        ),
    ]
