# Generated by Django 4.2 on 2023-05-11 16:42

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0058_alter_assignments_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='resubmission_requested',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignments',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 11, 16, 42, 41, 817209, tzinfo=datetime.timezone.utc)),
        ),
    ]
