# Generated by Django 4.2 on 2023-05-11 21:34

import datetime

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('teacher', '0059_assignments_resubmission_requested_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='created_at',
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 11, 21, 34, 18, 25467, tzinfo=datetime.timezone.utc)),
        ),
    ]
