# Generated by Django 4.2 on 2023-05-16 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0065_alter_assignments_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 16, 11, 46, 17, 862445, tzinfo=datetime.timezone.utc)),
        ),
    ]
