# Generated by Django 4.2 on 2023-06-07 00:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0068_alter_assignments_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 7, 0, 28, 49, 726681, tzinfo=datetime.timezone.utc)),
        ),
    ]
