# Generated by Django 4.2 on 2023-06-07 01:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0069_alter_assignments_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 7, 1, 40, 2, 443174, tzinfo=datetime.timezone.utc)),
        ),
    ]
