# Generated by Django 4.2.1 on 2023-06-26 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0072_alter_assignments_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 26, 16, 3, 58, 734868, tzinfo=datetime.timezone.utc)),
        ),
    ]
