# Generated by Django 4.2.1 on 2023-07-02 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0073_alter_assignments_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 2, 9, 59, 27, 85852, tzinfo=datetime.timezone.utc)),
        ),
    ]
