# Generated by Django 4.2.1 on 2023-07-05 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0075_alter_assignments_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 5, 13, 3, 9, 78182, tzinfo=datetime.timezone.utc)),
        ),
    ]
