# Generated by Django 4.2.1 on 2023-07-05 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0076_alter_assignments_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentmaterials',
            name='tenant_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assignments',
            name='tenant_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assignmentstudents',
            name='tenant_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courses',
            name='tenant_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 5, 13, 55, 28, 887140, tzinfo=datetime.timezone.utc)),
        ),
    ]
