# Generated by Django 4.2.1 on 2023-07-05 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0077_assignmentmaterials_tenant_id_assignments_tenant_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentmaterials',
            name='tenant_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 5, 14, 0, 59, 486431, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='tenant_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='assignmentstudents',
            name='tenant_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='tenant_id',
            field=models.IntegerField(null=True),
        ),
    ]
