# Generated by Django 4.2.1 on 2023-07-05 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0078_alter_assignmentmaterials_tenant_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 5, 14, 11, 11, 795617, tzinfo=datetime.timezone.utc)),
        ),
    ]
