# Generated by Django 4.2.1 on 2023-07-05 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0079_alter_assignments_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 5, 14, 12, 22, 7250, tzinfo=datetime.timezone.utc)),
        ),
    ]
