version: '3'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'originality_app'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ./mysql-data:/var/lib/mysql

  web:
    build: .
    restart: always
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:80"
    volumes:
      - .:/code
    ports:
      - 80:80
    depends_on:
      - db
