# Generated by Django 4.2.1 on 2023-07-05 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Institution',
            new_name='Tenant',
        ),
        migrations.AlterModelTable(
            name='tenant',
            table='tenants',
        ),
    ]
