# Generated by Django 4.2.1 on 2023-07-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_management', '0002_rename_institution_tenant_alter_tenant_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('tenant_id', models.IntegerField()),
            ],
            options={
                'unique_together': {('user_id', 'tenant_id')},
            },
        ),
    ]
