# Generated by Django 4.2.1 on 2023-07-05 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_management', '0003_usertenant'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tenant',
            table='tenant',
        ),
        migrations.AlterModelTable(
            name='usertenant',
            table='tenant_user',
        ),
    ]
