# Generated by Django 4.2.1 on 2023-07-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_management', '0004_alter_tenant_table_alter_usertenant_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertenant',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
