# Generated by Django 4.2.1 on 2023-07-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='tenant_id',
            field=models.IntegerField(default=0),
        ),
    ]
