# Generated by Django 4.2.1 on 2023-07-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_courses_tenant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='tenant_id',
            field=models.IntegerField(null=True),
        ),
    ]
