# Generated by Django 4.2 on 2023-05-11 09:31

import datetime

from django.db import migrations, models

class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Originality',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('setting', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OriginalityLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=100)),
                ('setting', models.TextField(max_length=50)),
                ('response', models.TextField(max_length=100)),
                ('success', models.TextField(max_length=15)),
                ('created_at', models.TextField(
                    default=datetime.datetime(2023, 5, 11, 9, 31, 47, 438618, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
