# Generated by Django 4.2 on 2023-05-09 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='originalitylog',
            name='response',
            field=models.TextField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='originalitylog',
            name='success',
            field=models.TextField(default=False, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='originalitylog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 9, 10, 18, 45, 630049, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='originalitylog',
            name='setting',
            field=models.TextField(max_length=50),
        ),
    ]
