# Generated by Django 4.2.1 on 2023-05-11 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originalitylog',
            name='created_at',
            field=models.TextField(default=datetime.datetime(2023, 5, 11, 10, 35, 52, 829370, tzinfo=datetime.timezone.utc)),
        ),
    ]
