# Generated by Django 4.2 on 2023-05-10 15:31

import datetime

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('settings_manager', '0002_originalitylog_response_originalitylog_success_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originalitylog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 10, 15, 31, 2, 116243, tzinfo=datetime.timezone.utc)),
        ),
    ]
