# Generated by Django 4.2 on 2023-05-10 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_manager', '0003_alter_originalitylog_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originalitylog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 10, 15, 34, 46, 580527, tzinfo=datetime.timezone.utc)),
        ),
    ]
