# Generated by Django 4.2.1 on 2023-06-26 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_manager', '0024_alter_originalitylog_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originalitylog',
            name='created_at',
            field=models.TextField(default=datetime.datetime(2023, 6, 26, 15, 42, 35, 830727, tzinfo=datetime.timezone.utc)),
        ),
    ]
