# Generated by Django 4.2.1 on 2023-07-02 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_manager', '0026_alter_originalitylog_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originalitylog',
            name='created_at',
            field=models.TextField(default=datetime.datetime(2023, 7, 2, 9, 59, 27, 82899, tzinfo=datetime.timezone.utc)),
        ),
    ]
