# Generated by Django 4.2.1 on 2023-07-05 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_manager', '0027_alter_originalitylog_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originalitylog',
            name='created_at',
            field=models.TextField(default=datetime.datetime(2023, 7, 5, 13, 0, 27, 34776, tzinfo=datetime.timezone.utc)),
        ),
    ]
