# Generated by Django 4.2.1 on 2023-07-05 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_manager', '0028_alter_originalitylog_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originalitylog',
            name='created_at',
            field=models.TextField(default=datetime.datetime(2023, 7, 5, 13, 3, 9, 77059, tzinfo=datetime.timezone.utc)),
        ),
    ]
