# Generated by Django 4.2.1 on 2023-07-05 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_manager', '0029_alter_originalitylog_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='originality',
            name='tenant_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='originalitylog',
            name='tenant_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='originalitylog',
            name='created_at',
            field=models.TextField(default=datetime.datetime(2023, 7, 5, 13, 55, 28, 882486, tzinfo=datetime.timezone.utc)),
        ),
    ]
