# Generated by Django 4.2.1 on 2023-07-05 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_manager', '0030_originality_tenant_id_originalitylog_tenant_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originality',
            name='tenant_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='originalitylog',
            name='created_at',
            field=models.TextField(default=datetime.datetime(2023, 7, 5, 14, 0, 59, 480346, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='originalitylog',
            name='tenant_id',
            field=models.IntegerField(null=True),
        ),
    ]
