# Generated by Django 4.2.1 on 2023-07-05 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_manager', '0032_alter_originalitylog_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originalitylog',
            name='created_at',
            field=models.TextField(default=datetime.datetime(2023, 7, 5, 14, 12, 22, 5781, tzinfo=datetime.timezone.utc)),
        ),
    ]
