# Generated by Django 4.2.1 on 2023-07-06 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_manager', '0034_alter_originalitylog_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originalitylog',
            name='created_at',
            field=models.TextField(default=datetime.datetime(2023, 7, 6, 6, 44, 0, 185737, tzinfo=datetime.timezone.utc)),
        ),
    ]
