# Generated by Django 4.2 on 2023-05-02 13:51

from django.db import migrations, models

class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigIntegerField(primary_key='id', serialize=False)),
                ('file_name', models.TextField(max_length=250)),
                ('sender_ip', models.TextField(max_length=50)),
                ('faculty_code', models.TextField(max_length=20)),
                ('faculty_name', models.TextField(max_length=50)),
                ('dept_code', models.TextField(max_length=50)),
                ('dept_name', models.TextField(max_length=50)),
                ('course_category', models.TextField(max_length=50)),
                ('course_code', models.TextField(max_length=50)),
                ('course_name', models.TextField(max_length=100)),
                ('ghost_writer_check', models.TextField(max_length=10)),
                ('link_moodle_file', models.TextField(max_length=250)),
                ('gov_student_id_md5', models.TextField(max_length=250)),
            ],
        ),
    ]
