# Generated by Django 4.2 on 2023-05-02 13:59

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('originality', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='assignment_code',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='submission',
            name='doc_sequence',
            field=models.TextField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='submission',
            name='file',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='submission',
            name='group_members',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='submission',
            name='lecturer_code',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='submission',
            name='moodle_assign_page_no',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='submission',
            name='student_code',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='submission',
            name='course_category',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='submission',
            name='course_code',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='submission',
            name='course_name',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='submission',
            name='dept_code',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='submission',
            name='dept_name',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='submission',
            name='faculty_code',
            field=models.TextField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='submission',
            name='faculty_name',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file_name',
            field=models.TextField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='submission',
            name='ghost_writer_check',
            field=models.TextField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='submission',
            name='gov_student_id_md5',
            field=models.TextField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.BigIntegerField(default='', primary_key='id', serialize=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='link_moodle_file',
            field=models.TextField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='submission',
            name='sender_ip',
            field=models.TextField(default='', max_length=50),
        ),
    ]
