# Generated by Django 4.2 on 2023-05-03 07:47

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('originality', '0002_submission_assignment_code_submission_doc_sequence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigIntegerField(default='', primary_key='id', serialize=False)),
                ('file', models.TextField(default='')),
                ('grade', models.TextField(default='', max_length=20)),
            ],
        ),
    ]
