# Generated by Django 4.2 on 2023-05-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('originality', '0005_submission_created_at_submission_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='owner_id',
            field=models.TextField(default='', max_length=50),
        ),
    ]
