# Generated by Django 4.2 on 2023-05-05 15:09

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('originality', '0007_submission_google_classroom_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='google_file_id',
            field=models.TextField(default='', max_length=100),
        ),
    ]
