# Generated by Django 4.2 on 2023-05-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('originality', '0008_submission_google_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='originality_id',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.BigAutoField(default='', primary_key=True, serialize=False),
        ),
    ]
