# Generated by Django 4.2 on 2023-05-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('originality', '0009_submission_originality_id_alter_submission_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.BigIntegerField(default='', primary_key='id', serialize=False),
        ),
    ]
