# Generated by Django 4.2 on 2023-05-10 15:31

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('originality', '0010_alter_submission_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
