# Generated by Django 4.2 on 2023-05-10 15:34

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('originality', '0011_alter_submission_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='originality_id',
            field=models.BigIntegerField(default=0, max_length=100),
        ),
    ]
