# Generated by Django 4.2 on 2023-05-11 09:20

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('originality', '0012_alter_submission_originality_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='originality_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
