# Generated by Django 4.2 on 2023-05-11 15:20

import django.utils.timezone
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('originality', '0013_alter_submission_originality_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='resubmission_created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
