# Generated by Django 4.2 on 2023-05-11 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('originality', '0014_submission_resubmission_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='resubmission_created_at',
            new_name='resubmission_requested',
        ),
    ]
