# Generated by Django 4.2 on 2023-06-07 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('originality', '0016_remove_submission_resubmission_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='assignment_id',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='report',
            name='doc_sequence',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='report',
            name='ghostwrite_report',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='report',
            name='user_id',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='submission',
            name='sender_ip',
            field=models.TextField(default='', max_length=250),
        ),
    ]
