# Generated by Django 4.2.1 on 2023-07-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('originality', '0022_report_report_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='tenant_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='tenant_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='tenant_id',
            field=models.IntegerField(default=0),
        ),
    ]
