# Generated by Django 4.2.1 on 2023-07-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('originality', '0023_grade_tenant_id_report_tenant_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='tenant_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='tenant_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='tenant_id',
            field=models.IntegerField(null=True),
        ),
    ]
